CREATE TABLE "admin_users" (
	"id" text PRIMARY KEY NOT NULL,
	"email" text NOT NULL,
	"password_hash" text NOT NULL,
	"nome" text DEFAULT '' NOT NULL,
	"criado_em" timestamp with time zone DEFAULT now() NOT NULL,
	CONSTRAINT "admin_users_email_unique" UNIQUE("email")
);
--> statement-breakpoint
CREATE TABLE "viaturas" (
	"id" text PRIMARY KEY NOT NULL,
	"marca" text NOT NULL,
	"marca_slug" text NOT NULL,
	"modelo" text NOT NULL,
	"modelo_slug" text NOT NULL,
	"versao" text DEFAULT '' NOT NULL,
	"preco" integer NOT NULL,
	"registo_mes" integer NOT NULL,
	"registo_ano" integer NOT NULL,
	"quilometros" integer NOT NULL,
	"lugares" integer NOT NULL,
	"portas" integer NOT NULL,
	"segmento" text NOT NULL,
	"combustivel" text NOT NULL,
	"potencia_cv" integer NOT NULL,
	"cilindrada_cc" integer NOT NULL,
	"transmissao" text NOT NULL,
	"cor" text DEFAULT '' NOT NULL,
	"cor_interior" text DEFAULT '' NOT NULL,
	"origem" text DEFAULT '' NOT NULL,
	"estado" text DEFAULT 'Usado' NOT NULL,
	"garantia" text DEFAULT '' NOT NULL,
	"livro_revisoes" boolean DEFAULT false NOT NULL,
	"segunda_chave" boolean DEFAULT false NOT NULL,
	"classe_portagem" text DEFAULT '' NOT NULL,
	"matricula" text DEFAULT '' NOT NULL,
	"vin" text DEFAULT '' NOT NULL,
	"fotos" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"extras" jsonb DEFAULT '[]'::jsonb NOT NULL,
	"destaque" boolean DEFAULT false NOT NULL,
	"estado_venda" text DEFAULT 'disponivel' NOT NULL,
	"iva_dedutivel" boolean DEFAULT false NOT NULL,
	"descricao" text DEFAULT '' NOT NULL,
	"criado_em" timestamp with time zone DEFAULT now() NOT NULL,
	"atualizado_em" timestamp with time zone DEFAULT now() NOT NULL
);
